### ISSUE TITLE
Could I have some clarification on the way the OrderEntry Interface works?

### ISSUE THREAD

**Issue by billystalnaker** [Intacct/intacct-sdk-php#109]
When updating a Sales Order in Intacct I see this code:
```
if ($this->getExternalId()) {
            $xml->writeAttribute('key', $this->getExternalId());
            $xml->writeAttribute('externalkey', 'true'); //TODO fix writeAttribute to accept bool
        } else {
            $xml->writeAttribute('key', $this->getTransactionId());
        }
```
The thing is I don't see `key` or `externalkey` anywhere on the Sales Order Transaction. I'm trying to figure out what I need to store in my database to make sure my key aligns with Intacct's key.

Also when updating a Sales Order Detail, or Line, I see:
`$xml->writeAttribute('line_num', $this->getLineNo());`

But all I see on the Sales Order Detail is the field `line_no` are these the same? Can these change? Are the just auto_incremented? Thanks in advance!

**Comment by jimmymcpeter** [comment]
`create_sotransaction` is used by the `OrderEntryTransactionCreate` class.  It's considered a legacy function since the OE transaction object has not been certified yet with the generic `create` function used by other classes.  Many of these legacy functions have an `externalid` field that are only set at creation.  You might set the externalid to be some identifier you used in an external system (ex `BillysID9876`).

If you wanted to update the OE transaction, instead of having to know and pass the Intacct transaction ID (ex `Sales Invoice-INV1234`) as the key value, you could set the external id and the system will lookup the appropriate record.

Not many folks use the externalid's since they aren't available with the newer API functions but I put it in there just in case someone wanted to still use it.

**Comment by jimmymcpeter** [comment]
When the create_sotransaction is successful, in the response we return
```xml
        <result>
            <status>success</status>
            <function>create_sotransaction</function>
            <controlid>7fb3eb5f-3ca0-46b1-8b5f-66b9abf7bf37</controlid>
            <key>Sales Invoice-INV0080</key>
        </result>
```
The `key` is what you need to use for the update

**Comment by billystalnaker** [comment]
Thanks @jimmymcpeter . What about the lines on the sales order? Are those keys returned as well?

**Comment by jimmymcpeter** [comment]
Line numbers can change, like if a user goes into the UI, edits the transaction and reorders the lines.  If you query the lines, the `RECORDNO` returned is the key/id you'd probably want to store.  Here's my query for the sales invoice i just made.  

```xml
        <readByQuery>
          <object>SODOCUMENTENTRY</object>
          <fields>*</fields>
          <query>DOCHDRID = 'Sales Invoice-INV0080'</query>
          <pagesize>100</pagesize>
          <docparid>Sales Invoice</docparid>
        </readByQuery>
```

response

```xml
<data listtype="sodocumententry" count="1" totalcount="1" numremaining="0" resultId="">
                <sodocumententry>
                    <RECORDNO>16</RECORDNO>
                    <DOCHDRNO>19</DOCHDRNO> <!-- this is the RECORDNO of the sales invoice -->
                    <DOCHDRID>Sales Invoice-INV0080</DOCHDRID>
                    <LINE_NO>0</LINE_NO> <!-- zero-based -->
                    <ITEMID>100</ITEMID>
<!--...-->
```

**Comment by billystalnaker** [comment]
Thanks @jimmymcpeter
