### ISSUE TITLE
How to Update Stock Numbers into intact using API

### ISSUE THREAD

**Issue by mepawan** [Intacct/intacct-sdk-php#140]
Hi,
I'm developer of Amin Hussain (Houston Direct Auto) USA. Amin has account into intact. As we can see Stock numbers in Intact account dashboard (as I have attached screenshot). We want to add/upload stock numbers to intact using api. 
I read api documentation here: https://developer.intacct.com/api/, 
but I didn't find any api endpoints or anything so that I can add/upload stock numbers to our intact dashboard. 

Can you please help & huide us how we can add/upload stock numbers using script(api). 

Thanks,
Pawan Developers

**Comment by jimmymcpeter** [comment]
Did you read the guides using the Intacct SDK for PHP?  https://developer.intacct.com/tools/sdk-php/

**Comment by jimmymcpeter** [comment]
Updating stock numbers might not be documented on the dev site for a reason (not supported, beta, etc).  I would [fill out the feedback form](https://docs.google.com/forms/d/e/1FAIpQLSf09LSiijHUZejqnzBSahTkAnhxgcJdr8vvoS6J4EXIvDPkWA/viewform?entry.1920380635=https%3A%2F%2Fdeveloper.intacct.com%2Fapi%2Finventory-control%2Fitems%2F) and ask for it to be added by the documentation team. Otherwise if you'd like a faster response, you can ask customer support via a case if it is supported.
